# 1. metadata
title: Katherine's Website
baseurl: "/wl-workshop"
url: ""

description: >- 
  Repo for constructing resume/CV & documenting professional
  data. Possibly will turn into portfolio once professional
  section done; unsure how structure will be then.

# 2. build settings
incremental: true
markdown: kramdown

exclude:
  - .sass-cache
  - _assets
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - tree.txt
  - assets/python
  - docs
  - node_modules
  - vendor

permalink: /:year/:month/:day/:title/

collections_dir: collections

# example setup
# collections:
#  collection-name:
#    output: true
#    permalink: /:collection/:slug/

# 3. assets
sass:
  sass_dir: "assets/css/_sass"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      order: 10
  - scope:
      path: ""
    values:
      layout: default

# defaults explained:
# 1. static images are in assets/img/*
# 2. by default, any pages/* document has
#    'order' var of value '10'
# 3. all pages have default layout unless
#    otherwise specified